name: E2E Tests

on:
  push:
    branches: [ master, feat-e2e-playwright-key-flows ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '19'

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package.json') }}
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps
        
      - name: Build application
        working-directory: ./frontend
        run: npm run build
        
      - name: Run E2E tests
        working-directory: ./frontend
        run: npm run test:e2e
        env:
          CI: true
        
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
          
      - name: Upload E2E test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: frontend/test-results/
          retention-days: 7
          
      - name: Upload E2E test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-videos
          path: frontend/test-results/
          retention-days: 7
          
      - name: Upload E2E test traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-traces
          path: frontend/test-results/
          retention-days: 7

  e2e-tests-mobile:
    name: E2E Tests Mobile
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package.json') }}
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps
        
      - name: Build application
        working-directory: ./frontend
        run: npm run build
        
      - name: Run E2E tests on mobile
        working-directory: ./frontend
        run: npx playwright test --project="Mobile Chrome" --project="Mobile Safari"
        env:
          CI: true
        
      - name: Upload mobile E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-mobile
          path: frontend/playwright-report/
          retention-days: 7

  e2e-tests-cross-browser:
    name: E2E Tests Cross Browser
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package.json') }}
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps
        
      - name: Build application
        working-directory: ./frontend
        run: npm run build
        
      - name: Run E2E tests on ${{ matrix.browser }}
        working-directory: ./frontend
        run: npx playwright test --project=${{ matrix.browser }}
        env:
          CI: true
        
      - name: Upload ${{ matrix.browser }} E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: frontend/playwright-report/
          retention-days: 7